//! IPC 契约类型导出（specta → `src/bindings.ts`）。
//!
//! 渐进：仅核心 payload；全量 `collect_commands!` 留后续批次。
//! 工程化：`pnpm gen:bindings` 写盘；`pnpm check:bindings` 再生 diff（见 ADR-006）。

use specta::TypeCollection;
use specta_typescript::Typescript;

use crate::progress::{InstallStage, ProgressPayload, ReadyPayload};
use crate::runtime::RuntimeStatus;
use crate::settings::{MirrorKind, ProxyMode};
use crate::system_runtime::{ActiveRuntimeKind, RuntimeSource};

/// 收集 R10 第一批契约类型。
pub fn collect_contract_types() -> TypeCollection {
    let mut types = TypeCollection::default();
    types
        .register::<InstallStage>()
        .register::<ProgressPayload>()
        .register::<ReadyPayload>()
        .register::<RuntimeStatus>()
        .register::<MirrorKind>()
        .register::<ProxyMode>()
        .register::<RuntimeSource>()
        .register::<ActiveRuntimeKind>();
    types
}

fn typescript_exporter() -> Typescript {
    Typescript::default().header(
        "// @generated by pnpm gen:bindings (specta) — do not edit by hand\n",
    )
}

/// 渲染 bindings 文本（不写盘）。
pub fn render_bindings() -> Result<String, String> {
    typescript_exporter()
        .export(&collect_contract_types())
        .map_err(|e| e.to_string())
}

/// 写出 `path`（供 `gen:bindings` / GEN_BINDINGS=1）。
pub fn export_bindings_to(path: impl AsRef<std::path::Path>) -> Result<(), String> {
    let body = render_bindings()?;
    if let Some(parent) = path.as_ref().parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(path.as_ref(), body).map_err(|e| e.to_string())
}

pub fn committed_bindings_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 仅当 `GEN_BINDINGS=1` 时写盘（`pnpm gen:bindings`）；日常 `cargo test` 不改仓库文件。
    #[test]
    fn write_bindings_when_gen_env_set() {
        if std::env::var("GEN_BINDINGS").ok().as_deref() != Some("1") {
            return;
        }
        let out = committed_bindings_path();
        export_bindings_to(&out).expect("export bindings.ts");
    }

    /// Freshness：再生文本须与已提交 `src/bindings.ts` 一致（勿在本测写盘）。
    #[test]
    fn bindings_match_committed_file() {
        let path = committed_bindings_path();
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            !committed.is_empty(),
            "missing src/bindings.ts — run: pnpm gen:bindings"
        );
        let rendered = render_bindings().expect("render bindings");
        assert_eq!(
            normalize_newlines(&rendered),
            normalize_newlines(&committed),
            "src/bindings.ts is stale — run: pnpm gen:bindings"
        );
        assert!(committed.contains("InstallStage"));
        assert!(committed.contains("ProgressPayload"));
        assert!(committed.contains("ReadyPayload"));
        assert!(committed.contains("RuntimeStatus"));
    }

    fn normalize_newlines(s: &str) -> String {
        s.replace("\r\n", "\n")
    }
}
