// @generated by pnpm gen:bindings (specta) — do not edit by hand

// This file has been generated by Specta. DO NOT EDIT.

export type ActiveRuntimeKind = "system" | "hosted"

/**
 * 安装 / 运维进度 stage（Rust 单一真源）。
 */
export type InstallStage = "detect" | "download-node" | "verify-node" | "extract-node" | "install-dsh" | "update-dsh" | 
/**
 * npm 流式行；UI 映射到 install-dsh，且常为 log-only
 */
"npm-log" | "start" | "reset" | "ready" | 
/**
 * 壳自更新；前端不映射到 Boot 步骤轨
 */
"shell-update"

export type MirrorKind = 
/**
 * npmmirror（Node + npm），国内默认
 */
"domestic" | 
/**
 * nodejs.org + registry.npmjs.org
 */
"official"

export type ProgressPayload = { stage: InstallStage; message: string; percent: number | null }

export type ProxyMode = "off" | "system" | "custom"

export type ReadyPayload = { url: string; port: number }

export type RuntimeSource = 
/**
 * auto：legacy；加载 settings 时迁移为 system 或 hosted
 */
"auto" | 
/**
 * 强制本机；失败则报错
 */
"system" | 
/**
 * 强制壳 AppData 托管
 */
"hosted"

export type RuntimeStatus = { nodeReady: boolean; harnessReady: boolean; 
/**
 * 入口缺失但已有依赖痕迹（中断更新等）
 */
harnessPartial: boolean; port: number; dshHome: string; effectiveDshHome: string; cleanProfileActive: boolean; appData: string; mirror: MirrorKind; proxyMode: ProxyMode; dshHomeOverride: string; closeToTray: boolean; runtimeSource: RuntimeSource; activeRuntime: ActiveRuntimeKind | null; systemRuntimeDetected: boolean; systemEntry: string | null; harnessVersion: string | null; harnessDigest: string | null; shellVersion: string }

